DROP TABLE COMMENT IF EXISTS;

CREATE TABLE COMMENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID INT NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);





